// Centralized route paths — never hardcode URL strings scattered across components.
export const paths = {
  home: "/",
  explorer: "/explorer",
  discover: "/decouvrir",
  becomePro: "/devenir-professionnel",
  contact: "/contact",
  cgv: "/cgv",
  legal: "/mentions-legales",
  privacy: "/confidentialite",
  cookies: "/cookies",
  login: "/connexion",
  register: "/inscription",
  forgotPassword: "/mot-de-passe-oublie",
  resetPassword: "/reinitialiser-mot-de-passe",
  proLogin: "/pro/connexion",
  adminLogin: "/admin/connexion",
  professional: (slug: string) => `/professionnel/${slug}`,

  app: "/app",
  favorites: "/favoris",
  follows: "/abonnements",
  garage: "/garage",
  bookings: "/reservations",
  notifications: "/notifications",
  settings: "/parametres",

  pro: "/pro",
  proOnboarding: "/pro/onboarding",
  proProfile: "/pro/profil",
  proServices: "/pro/prestations",
  proGallery: "/pro/galerie",
  proPosts: "/pro/publications",
  proBookings: "/pro/reservations",
  proCalendar: "/pro/calendrier",
  proClients: "/pro/clients",
  proStats: "/pro/statistiques",
  proSettings: "/pro/parametres",

  admin: "/admin",
  adminProfessionals: "/admin/professionnels",
  adminProspects: "/admin/prospects",
  adminUsers: "/admin/utilisateurs",
  adminBookings: "/admin/reservations",
  adminPosts: "/admin/publications",
  adminReviews: "/admin/avis",
  adminReports: "/admin/signalements",
  adminSettings: "/admin/parametres",
  adminLogs: "/admin/logs",
  adminContact: "/admin/messages",
};
